#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

# set -e


curl () {
  docker run --network fiware_default --rm appropriate/curl -s \
    "$@"
  printf "."
}

echo -e "⏳ Waiting for \033[1;34mOrion\033[0m to be available\n"
while [ `docker run --network fiware_default --rm appropriate/curl -s -o /dev/null -w %{http_code} 'http://orion:1026/version'` -eq 000 ]
do 
  echo -e "Context Broker HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://orion:1026/version'` " (waiting for 200)"
  sleep 1
done
printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:store001",
    "type": "Building",
    "category": {"type": "Property", "value": ["commercial"]},
    "address": {
      "type": "Property", 
      "value": {"streetAddress": "Bornholmer Straße 65","addressRegion": "Berlin","addressLocality": "Prenzlauer Berg","postalCode": "10439"},
      "verified": {"type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": {"type": "Point", "coordinates": [13.3986, 52.5547]}
    },
    "name": { "type": "Property", "value": "Bösebrücke Einkauf"
    },
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'




curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:store002",
    "type": "Building",
    "category": {"type": "Property", "value": ["commercial"]},
    "address": {
      "type": "Property", 
      "value": {"streetAddress":"Friedrichstraße 44","addressRegion":"Berlin","addressLocality":"Kreuzberg","postalCode":"10969"},
      "verified": {"type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": {"type": "Point", "coordinates": [13.3903,52.5075]}
    },
    "name": { "type": "Property", "value": "Checkpoint Markt"
    },
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:store003",
    "type": "Building",
    "category": {"type": "Property", "value": ["commercial"]},
    "address": {
      "type": "Property", 
      "value": {"streetAddress":"Mühlenstrasse 10","addressRegion":"Berlin","addressLocality":"Friedrichshain","postalCode":"10243"},
      "verified": {"type": "Property", "value": false}
    },
    "location": {
        "type": "GeoProperty",
        "value": {"type": "Point", "coordinates": [13.4447,52.5031]}
    },
    "name": { "type": "Property", "value": "East Side Galleria"
    },
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'


curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Building:store004",
    "type": "Building",
    "category": {"type": "Property", "value": ["commercial"]},
    "address": {
      "type": "Property", 
      "value": {"streetAddress":"Panoramastraße 1A","addressRegion":"Berlin","addressLocality":"Mitte","postalCode":"10178"},
      "verified": {"type": "Property", "value": false}
    },
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point", "coordinates": [13.4094,52.5208]}
    },
    "name": { "type": "Property", "value": "Tower Trödelmarkt"
    },
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

#
# Create a series of Shelf Entities and to be placed in each Store.
# Each shelf is designed to hold one product.
#



curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit001",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.3986112,52.554699]}
    },
    "maxCapacity": {"type": "Property","value": 50},
    "name": {"type": "Property","value": "Corner Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit002",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.3987221,52.554664]}
    },
    "maxCapacity": {"type": "Property","value": 100},
    "name": {"type": "Property","value": "Wall Unit 1"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit003",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.3987221,52.554664]}
    },
    "maxCapacity": {"type": "Property","value": 100},
    "name": {"type": "Property","value": "Wall Unit 2"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit004",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.390311,52.507522]}
    },
    "maxCapacity": {"type": "Property","value": 50},
    "name": {"type": "Property","value": "Corner Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit005",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.390309,52.50751]}
    },
    "maxCapacity": {"type": "Property","value": 100},
    "name": {"type": "Property","value": "Long Wall Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'


curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit006",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.4447112,52.503199]}
    },
    "maxCapacity": {"type": "Property","value": 50},
    "name": {"type": "Property","value": "Corner Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit007",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.4447221,52.503164]}
    },
    "maxCapacity": {"type": "Property","value": 100},
    "name": {"type": "Property","value": "Wall Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit008",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.4447221,52.503164]}
    },
    "maxCapacity": {"type": "Property","value": 100},
    "name": {"type": "Property","value": "Wall Unit 2"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit009",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.444711,52.503122]}
    },
    "maxCapacity": {"type": "Property","value": 50},
    "name": {"type": "Property","value": "Corner Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
    "id": "urn:ngsi-ld:Shelf:unit010",
    "type": "Shelf",
    "location": {
      "type": "GeoProperty",
      "value": {"type": "Point","coordinates": [13.4094111,52.5208028]}
    },
    "maxCapacity": {"type": "Property","value": 200},
    "name": {"type": "Property","value": "Long Wall Unit"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'


#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:001",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Beer"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:002",
  "type": "Product",
  "price": {"type": "Property","value": 10.99,"currency": "EUR"},
  "size": {"type": "Property","value": "M"},
  "name": {"type": "Property","value": "Red Wine"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:003",
  "type": "Product",
  "price": {"type": "Property","value": 14.99,"currency": "EUR"},
  "size": {"type": "Property","value": "M"},
  "name": {"type": "Property","value": "White Wine"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:004",
  "type": "Product",
  "price": {"type": "Property","value": 50.00,"currency": "EUR"},
  "size": {"type": "Property","value": "XL"},
  "name": {"type": "Property","value": "Vodka"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:005",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Lager"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:006",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Whisky"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:007",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Gin"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:008",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Apple Juice"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

curl -X POST \
  'http://orion:1026/ngsi-ld/v1/entities' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "id": "urn:ngsi-ld:Product:009",
  "type": "Product",
  "price": {"type": "Property","value": 0.99,"currency": "EUR"},
  "size": {"type": "Property","value": "S"},
  "name": {"type": "Property","value": "Orange Juice"},
    "@context": [
        "https://fiware.github.io/tutorials.Step-by-Step/datamodels-context.jsonld"
    ]
}'

echo -e " \033[1;32mdone\033[0m"
